from datetime import UTC, datetime

from dbt_cleaner.models import AnalysisConfig, SnowflakeObject


def generate_sql(
    config: AnalysisConfig,
    selected_schemas: list[tuple[str, str]],
    selected_objects: list[SnowflakeObject],
) -> str:
    ts = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = [
        f"-- Generated by dbt-cleaner on {ts}",
        f"-- Databases: {', '.join(config.databases)}",
        f"-- Connection: {config.connection_name}",
        f"-- Manifests: {', '.join(config.manifest_paths)}",
        "",
    ]

    if selected_schemas:
        lines += [
            "-- " + "=" * 60,
            "-- ORPHANED SCHEMAS (DROP CASCADE)",
            "-- " + "=" * 60,
        ]
        for db, schema in sorted(selected_schemas):
            lines.append(f"DROP SCHEMA IF EXISTS {db}.{schema} CASCADE;")
        lines.append("")

    if selected_objects:
        lines += [
            "-- " + "=" * 60,
            "-- ORPHANED OBJECTS",
            "-- " + "=" * 60,
        ]
        for obj in sorted(selected_objects, key=lambda o: (o.schema, o.name)):
            lines.append(obj.drop_sql())
        lines.append("")

    return "\n".join(lines)
